### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by edgarriba** [fxia22/stn.pytorch#16]
hi, I'm getting this error during the backward propagation:
```bash
Traceback (most recent call last):
  File "/home/eriba/code/main.py", line 259, in <module>
    main()
  File "/home/eriba/code/main.py", line 235, in main
    loss.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 152, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/home/eriba/software/stn.pytorch/script/functions/stn.py", line 72, in backward
    grad_input1 = grad_input1.cuda(self.device)
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 65, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /home/eriba/software/pytorch/pytorch/torch/lib/THC/generic/THCTensorCopy.c:18
```

Any idea why would that happen ?

**Comment by XuesongYang** [comment]
same here.

**Comment by chanmi** [comment]
same here.

**Comment by IngridLiu** [comment]
Hi,have you solved this problem?

**Comment by edgarriba** [comment]
@IngridLiu  switched to official pytorch functionality

**Comment by IngridLiu** [comment]
Thanks~ 
Do you mean that I should install pytorch from the official website?
I have installed pytorch follow the official website as bellow.
Linux; pip; python 2.7; cuda 8.0;

My GPU is GeForce GTX 1050,but I met the same error in GTX1080.

Could you tell me how to fix it more detailly?

Thank you very much!

**Comment by IngridLiu** [comment]
@edgarriba 
Thanks~
Do you mean that I should install pytorch from the official website?
I have installed pytorch follow the official website as bellow.
Linux; pip; python 2.7; cuda 8.0;

My GPU is GeForce GTX 1050,but I met the same error in GTX1080.

Could you tell me how to fix it more detailly?

Thank you very much!

**Comment by IceClear** [comment]
@IngridLiu Hi, I meet the same problem in test.py. Have you figured out the problem? Thanks.
