### ISSUE TITLE
How to use stn for 3D transform？

### ISSUE THREAD

**Issue by ixiaoli** [fxia22/stn.pytorch#25]
hi~ @fxia22 ,I want use stn for 3D transform？Could you give me some advice or some documents?
thank you!

**Comment by fxia22** [comment]
What modality are you dealing with? If you use point cloud, it is very easy, you can find my implementation [here](https://github.com/fxia22/pointnet.pytorch/blob/3700c44856c77aa520b4798bc12cf51eff55cd97/pointnet.py#L21-L38).

**Comment by CXiaoDing** [comment]
@ixiaoli hi, I also want to use STN for 3D transform, do you succeed?

**Comment by ixiaoli** [comment]
@CXiaoDing ,hi,you can look this: https://github.com/ankurhanda/gvnn and https://github.com/mariogeiger/se3cnn

**Comment by CXiaoDing** [comment]
thank you very much!!!@ixiaoli
